/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AImage: typeof import('ant-design-vue/es')['Image']
    ASlider: typeof import('ant-design-vue/es')['Slider']
    Cover: typeof import('./src/components/Cover.vue')['default']
    Grid: typeof import('./src/components/Grid.vue')['default']
    IconButton: typeof import('./src/components/IconButton.vue')['default']
    Nav: typeof import('./src/components/Nav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toolbar: typeof import('./src/components/Toolbar.vue')['default']
  }
}
